export enum ProviderCapability {
  ACCOUNT_RESOLUTION = 'ACCOUNT_RESOLUTION',
  ACCOUNT_DATA = 'ACCOUNT_DATA',
  TRANSACTION_DATA = 'TRANSACTION_DATA',
  BALANCE_DATA = 'BALANCE_DATA',
  TRANSACTION_VERIFICATION = 'TRANSACTION_VERIFICATION',
  WEBHOOKS = 'WEBHOOKS',
  PAYMENT_INITIATION = 'PAYMENT_INITIATION',
  IDENTITY = 'IDENTITY',
  OPEN_FINANCE = 'OPEN_FINANCE',
  BANKING = 'BANKING',
}
